# Generated by Django 4.1.3 on 2022-11-04 22:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.UUIDField(verbose_name='User identifier')),
                ('text', models.TextField(null=True, verbose_name='Answer (if textual)')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Question name')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Question order')),
                ('type', models.CharField(choices=[('STR', 'string'), ('SIN', 'single choice'), ('MUL', 'multiple choice')], max_length=3, verbose_name='Question type')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Choice name')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Choice order')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Survey name')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_end', models.DateField(null=True, verbose_name='End date')),
            ],
            options={
                'get_latest_by': 'date_start',
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(models.F('date_start'), name='date_start_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(models.F('date_end'), name='date_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.CheckConstraint(check=models.Q(('date_end', None), ('date_end__gt', models.F('date_start')), _connector='OR'), name='end_after_start'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question', verbose_name='Question to which is attached'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ManyToManyField(related_name='+', to='survey.questionchoice', verbose_name='Answer (if choice)'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question', verbose_name='Question to which is answered'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='questionchoice',
            order_with_respect_to='question',
        ),
        migrations.AddIndex(
            model_name='questionchoice',
            index=models.Index(fields=['question', 'order'], name='survey_ques_questio_d7ab4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionchoice',
            constraint=models.UniqueConstraint(models.F('question'), models.F('order'), name='choice_order_in_question'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='survey',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['survey', 'order'], name='survey_ques_survey__5b55d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(models.F('survey'), models.F('order'), name='question_order_in_survey'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='answer',
            order_with_respect_to='question',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(models.F('user'), name='user_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(models.F('user'), models.F('question'), name='answer_for_question'),
        ),
    ]
